name: ARISE

on:
  schedule:
    - cron: '05 7 * * *'
  workflow_dispatch:

jobs:
  run-Asta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Telegram Token and Chat ID
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV

    - name: Run Trading Bot and Capture Log
      run: |
        python main.py > trading.log 2>&1 || echo "Script gagal, cek log di bawah"
        cat trading.log

    - name: Publish Signals to Telegram
      if: always()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID:       ${{ secrets.CHAT_ID }}
      run: |
        # Ekstrak baris sinyal (mengandung '|')
        SIGNALS=$(grep '|' trading.log || true)
        if [ -n "$SIGNALS" ]; then
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            -d chat_id=${CHAT_ID} \
            -d text="$SIGNALS"
        else
          echo "No signals to send"
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

        git add .
        git commit -m "Auto-update by trading bot" || echo "No changes to commit"
        git pull --rebase origin main || echo "Pull gagal, kemungkinan tidak ada konflik"
        git push origin main || echo "Push gagal — silakan cek manual"
      env:
        GH_PAT:      ${{ secrets.GH_PAT }}
        GIT_ASKPASS: /dev/null
